default:
    image: hub.ilearned.eu/i-learned/ci-cd/pelican-builder
    before_script:
        - rm -rf ./..?* ./.[!.]* ./*
        - git clone https://gitlab.ilearned.eu/i-learned/blog/theme .
        - rm -rf content/*
        - git clone https://gitlab.ilearned.eu/i-learned/blog/content-fr.git -b $CI_COMMIT_REF_NAME content/
    tags:
        - AMD64

stages:
    - lint
    - test
    - test-deploy
    - prod-deploy

prettier:
    image: node:latest
    stage: lint
    allow_failure: true
    script:
        - apt update
        - apt install gettext sed
        - npm install -g prettier gettext-markdown
        - prettier . -w
        - bash updateTranslation.sh
        - git config --global user.email "contact@ilearned.eu"
        - git config --global user.name "Gitlab CI"
        - git add .
        - git commit -m "[🧹 Lint] Linted code and updated submodule"
        - git push https://CI_CD:$CI_GIT_USER_PASSWD@gitlab.ilearned.eu/i-learned/blog/theme.git
    only:
        - master

test-job:
    stage: test
    script:
        - pelican -o /tmp --fatal warnings
        - sh build.sh

prod-deploy-job:
    stage: prod-deploy
    script:
        - eval $(ssh-agent -s)
        - mkdir -p ~/.ssh
        - echo "$SSH_EBANVM01_PRIVATE_KEY" > ~/.ssh/id_ed25519
        - chmod 600 ~/.ssh/id_ed25519
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
        - sh build.sh
        - rsync -az --delete -e "ssh -i ~/.ssh/id_ed25519" output/ deploy@vm01.eban.eu.org:/var/www/ilearned-blog
    only:
        - master

test-deploy-job:
    image: hub.ilearned.eu/i-learned/ci-cd/pelican-builder-dev
    stage: test-deploy
    script:
        - sh build.sh
        - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --dir output
    only:
        - merge_requests
