default:
    image: hub.ilearned.eu/i-learned/ci-cd/blog-builder
    tags:
        - AMD64

stages:
    - updateTranslation
    - test
    - test-deploy
    - prod-deploy

updateTranslation:
    stage: updateTranslation
    allow_failure: true
    script:
        - rm -rf ./..?* ./.[!.]* ./*
        - git clone https://gitlab.ilearned.eu/i-learned/blog/content-fr .
        - bash ./updateTranslation.sh
        - git add .
        - git commit -m "[🧹 Lint] Updated translations"
        - git pull
        - git push https://CI_CD:$CI_GIT_USER_PASSWD@gitlab.ilearned.eu/i-learned/blog/content-fr.git
    rules:
        - if: $CI_COMMIT_BRANCH == "master" && $CI_COMMIT_AUTHOR != "Gitlab CI <contact@ilearned.eu>"

test-job:
    stage: test
    script:
        - rm -rf ./..?* ./.[!.]* ./*
        - git clone https://gitlab.ilearned.eu/i-learned/blog/theme .
        - rm -rf content/*
        - git clone https://gitlab.ilearned.eu/i-learned/blog/content-fr.git -b $CI_COMMIT_REF_NAME content/
        - LC_ALL="fr_FR.UTF-8" LC_CTYPE="fr_FR.UTF-8" pelican -o /tmp --fatal warnings
        - sh build.sh
    rules:
        - if: $CI_COMMIT_AUTHOR != "Gitlab CI <contact@ilearned.eu>"

prod-deploy-job:
    stage: prod-deploy
    script:
        - rm -rf ./..?* ./.[!.]* ./*
        - git clone https://gitlab.ilearned.eu/i-learned/blog/theme .
        - rm -rf content/*
        - git clone https://gitlab.ilearned.eu/i-learned/blog/content-fr.git -b $CI_COMMIT_REF_NAME content/
        - eval $(ssh-agent -s)
        - mkdir -p ~/.ssh
        - echo "$SSH_EBANVM01_PRIVATE_KEY" > ~/.ssh/id_ed25519
        - chmod 600 ~/.ssh/id_ed25519
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
        - sh build.sh
        - rsync -az --delete -e "ssh -i ~/.ssh/id_ed25519" output/ deploy@vm01.eban.eu.org:/var/www/ilearned-blog
    rules:
        - if: $CI_COMMIT_BRANCH == "master" && $CI_COMMIT_AUTHOR != "Gitlab CI <contact@ilearned.eu>"

test-deploy-job:
    stage: test-deploy
    script:
        - rm -rf ./..?* ./.[!.]* ./*
        - git clone https://gitlab.ilearned.eu/i-learned/blog/theme .
        - rm -rf content/*
        - git clone https://gitlab.ilearned.eu/i-learned/blog/content-fr.git -b $CI_COMMIT_REF_NAME content/
        - sh build.sh
        - echo $NETLIFY_SITE_ID $NETLIFY_AUTH_TOKEN
        - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --dir output
    only:
        - merge_requests
